# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spreex
email: spreex@my-data.space
description: Spree Commerece extensions catalogue
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spreex.github.io"
enforce_ssl: spreex.github.io

api_url: "https://api.my-data.space"
api_websocket_url: "https://api.my-data.space:8443"
client_id: "3091a439-33da-10da-e7f0-4dc2b52bafde"

# Build settings
markdown: kramdown

exclude:
  - test
  - karma.conf.js
  - vendor/bootstrap/stylesheets
  - vendor/fa/scss
  - gulpfile.js
  - package.json
  - bower.json
  - node_modules
  - bower_components
  - README.md
  - jquery

gems:
  - jekyll-redirect-from
